### PR TITLE
feature no-video quantums

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by ablanco** [comment]
@jespino This pull request has conflicts with the mathjax code. Now that mathjax is in master, this can no longer be merged. Can you update this code?

**Comment by jespino** [comment]
Sure

**Comment by jespino** [comment]
Now is ready :)

**Comment by ablanco** [comment]
@jespino Problems detected:
1. Video processing fails. The functions (celery tasks) that download the last frame of YouTube no longer work.
   - Also, if the media is not a YT video and the teachers adds a questions to the nugget, the system tries to use the last frame image, which doesn't exist. It should download Vimeo videos and extract the last frame, and it should force the blank canvas usage if the media is Prezi or Scribd.
2. There is no thumbnail for Scribd or Prezi elements in Unit list. It looks ugly, there should be a thumbnail that opened a preview.
3. The Content Id field should be Content Url. It should let the teacher paste a whole url, and extract the ID automatically.
4. When viewing a question the Show video button should have a new text. Now it isn't always a video.
5. If a Prezi presentation with autoplay ends, it should load the exercise automatically (if possible), instead of looping.
6. Cannot navigate to P2P. Cannot read property 'bind' of undefined. The only way to arrive to a P2P exercise is letting its nugget's video finish. Loading the P2P directly by the url, or using the side navigation menu, doesn't work.
7. If the solution is not a text, if it is a media content, then it doesn't load. The nugget's media loads instead.

**Comment by ablanco** [comment]
@jespino I found some problems:
1. In a nugget with a YT video that has a question, if you choose to use the last_frame as background it doesn't work. In the teacheradmin you can choose, but in the classroom the blank canvas is always shown.
2. In a nugget with a YT video and a question that is using the last_frame, then if you switch to another media type that cannot use a last_frame, the teacheradmin doesn't refresh and in the question tab the last_frame option is still selected and shown. Changing the content type should refresh the question tab controls properly.
3. If the teacher introduces a wrong url for a content type, it should be detected in the JS and show an error when saving the nugget. Now it gets stores and it fails at the classroom view. Some basic url validation related to the content type is required.
4. There is a button in the question tab with the message "Use video as solution", this no longer applies and should be changed since it can be a Prezi or Scribd content.
5. The attributes in the Backbone models that are a direct representation of the Django model ones should share the same name.
   - This means no camel case for Django-like attributes, use _ an lower case instead.
   - For attributes that only exists in the Backbone model we use came case and prepend a _ to the name, this helps differentiating attributes that are present in the backend.
   - We didn't start the project doing this (a mistake), but we are trying to do it now. It would be great if you could change the fields' names.

**Pull request merged**
