### PR TITLE
Openbadges integration

### PR DESCRIPTION
**Pull request by yamila-moreno**
This PR includes integration with Mozilla Openbadges. 

There's no visualization for the badges, due there was no specification for that pages, but the integration functionality is complete.

### CODE REVIEW

**Comment by oscarcp** [comment]
Hi Yamila!,

Could you please compleete this pull request with a bit of documentation please? like p.e. what's supposed to be in the BADGES_BASE_URL :)

**Comment by oscarcp** [comment]
The migration scripts are broken:
Running migrations for courses:
- Migrating forwards to 0015_calculate_stats.
  > courses:0014_auto__add_unique_course_slug__add_unique_announcement_slug
  FATAL ERROR - The following SQL query failed: ALTER TABLE "courses_course" ADD CONSTRAINT "courses_course_slug_uniq" UNIQUE ("slug")
  The error was: no se pudo crear el índice único «courses_course_slug_uniq»
  DETAIL:  La llave (slug)=() está duplicada.

**Comment by pitbulk** [comment]
@yamila-moreno  any advance on the documentation?  

Regards

**Comment by yamila-moreno** [comment]
@oscarcp it seems in your database you have empty or duplicated slugs, but slugs should be unique. It's necessary first to fix data.

@pitbulk I'm on it! (sorry for the inconvenience)

**Comment by yamila-moreno** [comment]
Attached some documentation. Sorry for the delay.

**Comment by jespino** [comment]
Falta, la migración de los objetos Award, extraer el Issuer a unos campos del settings, traducir las cadenas al español, cambiar la vista de backbone por un handler jquery y cambiar el "Add to backpack" por un boton de bootstrap.

**Pull request merged**
