### PR TITLE
General fix and improvements

### PR DESCRIPTION
**Pull request by neokore**

### CODE REVIEW

**Comment by pitbulk** [comment]
O_o

**Comment by jespino** [comment]
I love small pull requests like this. Is really easy to review.

**Comment by goinnn** [comment]
+1

**Comment by ablanco** [comment]
That's a big pull request if ever seen one. Could you provide a list of features included at least?

**Comment by neokore** [comment]
Sorry guys, that was a mistake creating a pull request for a fork.
Great comments anyway! :)

**Pull request closed without merging**
