### PR TITLE
Feature assets

### PR DESCRIPTION
**Pull request by fid-jose**
This branch adds the option of creating assets and make them avaliable through KnowledgeQuantums to the students.
An asset can be defined as an external resource which might be used by students.
The maximun number of reservations each student can do can be defined by each course. The dates on which assets can be booked can be defined by KQ.

### CODE REVIEW

**Comment by ablanco** [comment]
We need some documentation about this pull request before merging it. We need to test it, and for that we need to know what it does, how to use it, how to configure it, new settings, etc.

This is a huge pull request, with thousands of lines changed. We need to proceed carefully and test it thoroughly before accepting it. And for that we need comprehensive documentation.

**Comment by fid-jose** [comment]
In order to test it, you just have to run the migrations.
Where should we write the documentation about how to configure and use it, in teachers_manual.rst?

**Comment by ablanco** [comment]
install.rst if this feature requires new dependencies, but I think is not the case
configuration.rst for the settings and other configuration-related changes
teacher_manual.rst for the use of the feature from a teacher point of view (administration)

There is no need for student's documentation, the system should be easy enough ot use so the students can figure it out by themselves. I know this is not the case for moocng yet, but we are making improvements in that direction.

**Comment by ablanco** [comment]
I found some problems:

**General**
- Missing translations.
- If the granularity of the slots change, the slot duration of the existing assets doesn't get updated properly.

**Teacher administration**
- In the asset tab, in teacher admin, the space utilization is quite poor. That UI need to be improved, there is no point in using a span4 class there.
- The "add asset" button should load the asset tab after rerendering the KQ editor, like the "add question" button does.

**Classroom**
- The headers used in the asset view in classroom are h2, which is the same level than the nugget's header. They must be smaller, like h3, h4 and so on.
- The "next" button doesn't navigate to the asset, it jumps to the next nugget if available.
- When the video ends the asset isn't automatically loaded.
- In the "book asset" modal, the information about the asset is repeated. Why?
- Confirming the reservation sends the user to the reservation page, it should not leave the classroom view automatically. It should follow the same pattern than the peer review component.
- In the reservations page, why has the "remove button" a span4 class applied? The button doesn't look very well in that position.

**Comment by ablanco** [comment]
@fid-jose @davidjgc1  There is an important problem. I have just realized that the students' reservations are stored in the postgresql.

This goes against the project's policy, all the students' input must be stored in the mongodb. Since there are thousand students in each course, the reservations records will be huge, to keep the machines stress to a minimum and to help escalating the system we chose mongodb for this data.

The reservations must be stored in a mongodb collection.

**Comment by pitbulk** [comment]
We plan to add your branch in our master,

Can you merge the master branch in feature-assets?
Also please, rename your migrations, put then after our (10,11) migrations

**Comment by fid-jose** [comment]
@ablanco

> Missing translations.

We were planning to add them after merging. However, they are included in the current version.

> If the granularity of the slots change, the slot duration of the existing assets doesn't get updated properly.

In the assets admin page, there's an option to check and correct the duration of the assets. This action can be applied to all assets at once if the admin orders so. This is not done automatically as it can mean modifying or cancelling lots of reservations.

> Teacher administration

We made some changes in the teacher administration interface that solve the problems mentioned in your comment.

> Classroom:
> The headers used in the asset view in classroom are h2, which is the same level than the nugget's header. They must be smaller, like h3, h4 and so on.
> The "next" button doesn't navigate to the asset, it jumps to the next nugget if available.
> When the video ends the asset isn't automatically loaded.
> In the reservations page, why has the "remove button" a span4 class applied? The button doesn't look very well in that position.

This has been fixed.

> In the "book asset" modal, the information about the asset is repeated. Why?

The information is not repeated. It shows the same information that is available in the assets page so the user has this information when choosing which time to book.

> Confirming the reservation sends the user to the reservation page, it should not leave the classroom view automatically. It should follow the same pattern than the peer review component.

This is yet to be changed, but it can be changed after the merge.

@pitbulk 

> Can you merge the master branch in feature-assets?
> Also please, rename your migrations, put then after our (10,11) migrations

Done :)

**Pull request merged**
